openapi: 3.0.0
info:
  title: sessions
  version: '1.0'
  description: API for User Signup/Signin
  contact:
    name: Magnetic Asia
    url: 'https://www.magneticasia.com/'
    email: info@magneticasia.com
  termsOfService: 'https://www.magneticasia.com/terms-conditions.html'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://magneticasia.stoplight.io/mocks/magneticasia/openapi-sessions/1646925'
    description: Stoplight Mock Server
tags:
  - name: Sessions API
    description: Sessions CRUD and related stuff.
paths:
  /session-event-types:
    get:
      summary: get-session-event-types
      tags:
        - Sessions API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Type - Alpha
                    id:
                      type: number
                      minimum: 1
              examples:
                example-1:
                  value:
                    - id: 1
                      name: Type - Alpha
                    - id: 2
                      name: Type - Bravo
                example-2:
                  value:
                    - name: Type - Alpha
                      id: 1
      operationId: get-session-event-types
      description: Get the list of session-event types.
      parameters: []
  /session-event-categories:
    get:
      summary: get-session-event-categories
      tags:
        - Sessions API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Type - Alpha
                    sub-categories:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          id:
                            type: number
                            minimum: 1
                    id:
                      type: number
                      minimum: 1
              examples:
                example-1:
                  value:
                    - id: 1
                      name: Category - Alpha
                      sub-categories:
                        - id: 4
                          name: Sub-Category - Alpha 1.1
                    - id: 2
                      name: Category - Bravo
                      sub-categories:
                        - id: 5
                          name: Sub-Category - Bravo 1.1
                        - id: 6
                          name: Sub-Category - Bravo 1.2
                    - id: 3
                      name: Category - Charlie
                      sub-categories:
                        - id: 7
                          name: Sub-Category - Charlie 1.1
      operationId: get-session-event-categories
      description: Get the list of session-event categories.
      parameters: []
  /organisation-name:
    get:
      summary: get-organisation-name
      tags:
        - Sessions API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
              examples:
                example-1:
                  value:
                    name: Organisation - Alpha
      operationId: get-organisation-name
      description: Get the organisation name of the user.
      parameters: []
  /sessions:
    get:
      summary: get-sessions
      tags:
        - Sessions API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      minimum: 1
                    name:
                      type: string
              examples:
                example-1:
                  value:
                    - id: 1
                      name: Session - Alpha
                    - id: 2
                      name: Session - Bravo
      operationId: get-sessions
      description: Session list.
    post:
      summary: post-sessions
      tags:
        - Sessions API
      operationId: post-sessions
      responses:
        '201':
          description: Created
      description: Session create data.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                session_name:
                  type: string
                session_event_type:
                  type: number
                  minimum: 1
                session_event_categories:
                  type: array
                  items:
                    type: number
                    minimum: 1
                session_tags:
                  type: array
                  items:
                    type: string
                organisation_name:
                  type: string
                  example: Organisation - Alpha
                session_timing:
                  type: string
                  enum:
                    - once
                    - series
                  example: once
                start_end_datetimes:
                  type: array
                  items:
                    type: object
                    properties:
                      start_datetime:
                        type: string
                        example: '2099-12-25 13:00:00'
                      end_datetime:
                        type: string
                        example: '2099-12-25 17:00:00'
                    required:
                      - start_datetime
                      - end_datetime
              required:
                - session_name
                - session_event_type
                - session_event_categories
                - organisation_name
                - session_timing
                - start_end_datetimes
            examples:
              example-1:
                value:
                  session_name: Session - Alpha
                  session_event_type: 1
                  session_event_categories:
                    - 4
                    - 5
                  session_tags:
                    - tag - alpha
                    - tag - bravo
                  organisation_name: Organisation - Alpha
                  session_timing: once
                  start_end_datetimes:
                    - start_datetime: '2099-12-25 13:00:00'
                      end_datetime: '2099-12-25 17:00:00'
              example-2:
                value:
                  session_name: Session - Bravo
                  session_event_type: 1
                  session_event_categories:
                    - 4
                    - 5
                  session_tags:
                    - tag - alpha
                    - tag - bravo
                  organisation_name: Organisation - Bravo
                  session_timing: series
                  start_end_datetimes:
                    - start_datetime: '2099-12-25 13:00:00'
                      end_datetime: '2099-12-25 17:00:00'
                    - start_datetime: '2099-12-27 13:00:00'
                      end_datetime: '2099-12-27 17:00:00'
                    - start_datetime: '2099-12-29 13:00:00'
                      end_datetime: '2099-12-29 17:00:00'
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: JWT
